name: Site Build

on:
  push:
    branches:
      - main
      - setup-pages-index-build

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./public
          enable_jekyll: false
